---
title: "``stat_fit_augment``:  Augment data with fitted values and statistics"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggpmisc)
library(dplyr)
library(magrittr)
```


### Description
stat_fit_augment fits a model and returns the data augmented with information from the fitted
model, using package *broom*

#### Usage 
<pre><code>
stat_fit_augment(mapping = NULL, data = NULL, geom = "smooth", method = "lm", method.args = list(formula = y ~ x),
augment.args = list(), level = 0.95, y.out = ".fitted", position = "identity", na.rm = FALSE, show.legend = FALSE,
inherit.aes = TRUE, ...)
</code></pre>

### Arguments

* ``mapping``: The aesthetic mapping, usually constructed with aes or aes_. Only needs to be
set at the layer level if you are overriding the plot defaults.
* ``data ``: A layer specific dataset - only needed if you want to override the plot defaults.
* ``geom`` The geometric object to use display the data method character.
* ``method.args`` list of arguments to pass to method.
* ``augment.args`` list of arguments to pass to broom:augment.
* ``level`` numeric Level of confidence interval to use (0.95 by default)
* ``y.out`` character (or numeric) index to column to return as y.
* ``position``: The position adjustment to use for overlapping points on this layer
* na.rm logical indicating whether NA values should be stripped before the computation proceeds.
* ``show.legend ``: logical. Should this layer be included in the legends? NA, the default, includes if
any aesthetics are mapped. FALSE never includes, and TRUE always includes.
* ``inherit.aes`` If FALSE, overrides the default aesthetics, rather than combining with them. This is most useful for helper functions that define both data and aesthetics and shouldn't inherit behaviour from the default plot specification, e.g. borders.
* ``...``:   Other arguments passed on to layer. This can include aesthetics whose values you want to set, not map. See layer for more details..

####Computed variables

The output of augment is returned as is, except for y which is set based on y.out and y.observed which preserves the y returned by the broom::augment methods. This renaming is needed so that the geom works as expected.

#### Note
The statistics stat_fit_augment accepts only methods that accept formulas under any formal parameter name and a data argument. Use ggplot2::stat_smooth() instead of stat_fit_augment in production code if the additional features are not needed. At the moment stat_fit_augment is
under development and may change.










