stat_fit_tidy One row data frame with fitted parameter estimates

### Description
stat_fit_tidy fits a model and returns a "tidy" version of the model’s summary, using package ’broom’.

#### Usage 

<pre><code>
stat_fit_tidy(mapping = NULL, data = NULL, geom = "null", method = "lm", method.args = list(formula = y ~ x), label.x.npc = "left", label.y.npc = "top", label.x = NULL, label.y = NULL, position = "identity", na.rm = FALSE, show.legend = FALSE, inherit.aes = TRUE, ...)
</code></pre>

### Arguments

* ``mapping``: The aesthetic mapping, usually constructed with aes or aes_. Only needs to be
set at the layer level if you are overriding the plot defaults.
* ``data ``: A layer specific dataset - only needed if you want to override the plot defaults.
geom The geometric object to use display the data method character.
* method.args list of arguments to pass to method.
* label.x.npc, label.y.npc numeric with range 0..1 or character. Coordinates to be used for positioning the
output, expressed in "normalized parent coordinates" or character string. If too short they will be recycled.
* label.x, label.y numeric Coordinates (in data units) to be used for absolute positioning of the
output. If too short they will be recycled.
* ``position``: The position adjustment to use for overlapping points on this layer
* ``na.rm``: a logical indicating whether NA values should be stripped before the computation proceeds.
* ``show.legend ``: logical. Should this layer be included in the legends? NA, the default, includes if any aesthetics are mapped. FALSE never includes, and TRUE always includes.
* inherit.aes If FALSE, overrides the default aesthetics, rather than combining with them.
This is most useful for helper functions that define both data and aesthetics and shouldn’t inherit behaviour from the default plot specification, e.g. borders.
* ``...``:   Other arguments passed on to layer. This can include aesthetics whose values you want to set, not map. See layer for more details..

#### Computed variables

The output of tidy is returned after reshaping it into a single row. Grouping is respected, and the
model fit separatately to each group of data. The returned data object has one row for each group
within a panel.
