
## 1. WVPlots
* Win-Vector Consulting LLC
* Nina Zumel and John Mount

WVPlots: Common Plots for Analysis

Select data analysis plots, under a standardized calling interface implemented on top of 'ggplot2' and 'plotly'. Plots of interest include: 'ROC', gain curve, scatter plot with marginal distributions, conditioned scatter plot with marginal densities, box and stem with matching theoretical distribution, and density with matching theoretical distribution.


Plots created by WVplots are "ggplot" objects
Therefore you can use the regular ggplot syntax with them.

* ROC Cuves
* Gain Curves
* Shaded Density Plot

## 2. GGally

GGally: Extension to 'ggplot2'

The R package 'ggplot2' is a plotting system based on the grammar of graphics. 'GGally' extends 'ggplot2' by adding several functions to reduce the complexity of combining geometric objects with transformed data. Some of these functions include a pairwise plot matrix, a two group pairwise plot matrix, a parallel coordinates plot, a survival plot, and several functions to plot networks.


## 3. ggcorrplot

The 'ggcorrplot' package can be used to visualize easily a correlation matrix using 'ggplot2'. It provides a solution for reordering the
correlation matrix and displays the significance level on the plot. 

It also includes a function for computing a matrix of correlation p-values.

## 4. ggfortify

ggfortify: Data Visualization Tools for Statistical Analysis Results

Unified plotting tools for statistics commonly used, such as GLM, time series, PCA families, clustering and survival analysis. The package offers a single plotting interface for these analysis results and plots in a unified style using 'ggplot2'.

## 5. ggalt

ggalt: Extra Coordinate Systems, 'Geoms', Statistical Transformations, Scales and Fonts for 'ggplot2'

A compendium of new geometries, coordinate systems, statistical transformations, scales and fonts for 'ggplot2', including splines, 1d and 2d densities, univariate average shifted histograms, a new map coordinate system based on the 'PROJ.4'-library along with ``geom_cartogram()`` that mimics the original functionality of ``geom_map()``, formatters for "bytes", a ``stat_stepribbon()`` function, increased 'plotly' compatibility and the 'StateFace' open source font 'ProPublica'. 

Further new functionality includes lollipop charts, dumbbell charts, the ability to encircle points and coordinate-system-based text annotations.


