
partial.rfsrc randomForestSRC partial dependence (data object) (modified from
randomForestSRC V1.6.0)
#### Description 

calculate the partial dependence of an x-variable on the class probability (classification), response
(regression), mortality (survival), or the expected years lost (competing risk) from a RF-SRC analysis.
#### Usage 
<pre><code>

partial.rfsrc(x, xvar.names, which.outcome, surv.type = c("mort", "rel.freq",
"surv", "years.lost", "cif", "chf"), nvar, npts = 25, subset, granule = 5,
...)
34 partial.rfsrc

</code></pre>
#### Arguments

x An object of class (rfsrc, grow), (rfsrc, synthetic), (rfsrc, predict).
xvar.names Names of the x-variables to be used.
which.outcome For classification families, an integer or character value specifying the class to
focus on (defaults to the first class). For competing risk families, an integer
value between 1 and J indicating the event of interest, where J is the number of
event types. The default is to use the first event type.
surv.type For survival families, specifies the predicted value. See details below.
nvar Number of variables to be plotted. Default is all.
npts Maximum number of points used when generating partial plots for continuous
variables.
subset Vector indicating which rows of the x-variable matrix x$xvar to use. All rows
are used if not specified.
granule Integer value controlling minimum number of unique values required to treat a
variable as continuous. If there are fewer, the variable is treated as a factor
... other used 
</code></pre>
#### Arguments
. Included for compatibility with plot.variable calls.
Details
The vertical axis displays the ensemble predicted value, while x-variables are plotted on the horizontal
axis.
1. For regression, the predicted response is used.
2. For classification, it is the predicted class probability specified by which.outcome.
3. For survival, the choices are:
*  Mortality (mort).
*  Relative frequency of mortality (rel.freq).
*  Predicted survival (surv)
4. For competing risks, the choices are:
*  The expected number of life years lost (years.lost).
*  The cumulative incidence function (cif).
*  The cumulative hazard function (chf).
In all three cases, the predicted value is for the event type specified by which.outcome.
The y-value for a variable X, evaluated at X = x, is
~ f(x) =
1
n
Xn
i=1
^ f(x; xi;o);
where xi;o represents the value for all other variables other than X for individual i and ^ f is the
predicted value. Generating partial plots can be very slow. Choosing a small value for npts can
speed up computational times as this restricts the number of distinct x values used in computing ~ f.
Calculating partial dependence data can be slow. Setting npts to a smaller number can help.
partial.rfsrc 35
Author(s)
Hemant Ishwaran and Udaya B. Kogalur (Modified by John Ehrlinger)

See Also
rfsrc, rfsrcSyn, predict.rfsrc
#### Examples 
```{r} 

## ------------------------------------------------------------
## survival/competing risk
## ------------------------------------------------------------
## survival
## Not run:
data(veteran, package = "randomForestSRC")
v.obj <- rfsrc(Surv(time,status)~., veteran, nsplit = 10, ntree = 100)
plot.variable(v.obj, plots.per.page = 3)
plot.variable(v.obj, plots.per.page = 2, xvar.names = c("trt", "karno", "age"))
plot.variable(v.obj, surv.type = "surv", nvar = 1)
plot.variable(v.obj, surv.type = "surv", partial = TRUE, smooth.lines = TRUE)
plot.variable(v.obj, surv.type = "rel.freq", partial = TRUE, nvar = 2)
## example of plot.variable calling a pre-processed plot.variable object
p.v <- plot.variable(v.obj, surv.type = "surv", partial = TRUE, smooth.lines = TRUE)
plot.variable(p.v)
p.v$plots.per.page <- 1
p.v$smooth.lines <- FALSE
plot.variable(p.v)
## End(Not run)
## Not run:
## competing risks
data(follic, package = "randomForestSRC")
follic.obj <- rfsrc(Surv(time, status) ~ ., follic, nsplit = 3, ntree = 100)
plot.variable(follic.obj, which.outcome = 2)
## End(Not run)
## ------------------------------------------------------------
## regression
36 plot.gg_error
## ------------------------------------------------------------
## Not run:
## airquality
airq.obj <- rfsrc(Ozone ~ ., data = airquality)
plot.variable(airq.obj, partial = TRUE, smooth.lines = TRUE)
## motor trend cars
mtcars.obj <- rfsrc(mpg ~ ., data = mtcars)
plot.variable(mtcars.obj, partial = TRUE, smooth.lines = TRUE)
## End(Not run)
## ------------------------------------------------------------
## classification
## ------------------------------------------------------------
## iris
#rfsrc_iris <- rfsrc(Species ~., data = iris)
#data(rfsrc_iris, package="ggRandomForests")
#gg_dta <- partial.rfsrc(rfsrc_iris, )
## Not run:
## motor trend cars: predict number of carburetors
mtcars2 <- mtcars
mtcars2$carb <- factor(mtcars2$carb,
labels = paste("carb", sort(unique(mtcars$carb))))
mtcars2.obj <- rfsrc(carb ~ ., data = mtcars2)
plot.variable(mtcars2.obj, partial = TRUE)
## End(Not run)
