
plot.gg_survival Plot a gg_survival object.
#### Description 

Plot a gg_survival object.
#### Usage 
<pre><code>

## S3 method for class 'gg_survival'
plot(x, type = c("surv", "cum_haz", "hazard", "density",
"mid_int", "life", "proplife"), error = c("shade", "bars", "lines", "none"),
...)

</code></pre>
#### Arguments

x gg_survival or a survival gg_rfsrc object created from a rfsrc object
type "surv", "cum_haz","hazard","density","mid_int", "life","proplife"
error "shade", "bars", "lines" or "none"
... not used
Value
ggplot object
#### Examples 
```{r} 

## Not run:
## -------- pbc data
data(pbc, package="randomForestSRC")
pbc$time <- pbc$days/364.25
# This is the same as kaplan
gg_dta <- gg_survival(interval="time", censor="status",
data=pbc)
plot(gg_dta, error="none")
plot(gg_dta)
# Stratified on treatment variable.
gg_dta <- gg_survival(interval="time", censor="status",
data=pbc, by="treatment")
plot(gg_dta, error="none")
plot(gg_dta)
# ...with smaller confidence limits.
gg_dta <- gg_survival(interval="time", censor="status",
plot.gg_variable 55
data=pbc, by="treatment", conf.int=.68)
plot(gg_dta, error="lines")
## End(Not run)
